apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartogram-deployment
spec:
  selector:
    matchLabels:
      app: cartogram
  replicas: 1
  template:
    metadata:
      labels:
        app: cartogram
        env: development
    spec:
      containers:
        - name: cartogram
          image: gcr.io/cartogram/app:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "4000"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ENV
              value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: cartogram-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: cartogram
